language: node_js
node_js:
  - '10'

branches:
  only:
    - master

jobs:
  include:
    - script: ./test
    - stage: verify changes
      if: type = push
      script: ./verify-changes
    - stage: publish
      if: type = push
      script: ./publish
